resources:
  - ./analyzer-service.yml
  - ./analyzer-stateful-set.yml
  - ./analyzer-train-service.yml
  - ./analyzer-train-stateful-set.yml
  - ./api-deployment.yml
  - ./api-service.yml
  - ./index-deployment.yml
  - ./index-service.yml
  - ./jobs-deployment.yml
  - ./jobs-services.yml
  - ./migrations-job.yml
  - ./uat-deployment.yml
  - ./uat-service.yml
  - ./ui-deployment.yml
  - ./ui-service.yml
  - ./gateway-ingress.yml

images:
  - name: service-auto-analyzer
    newName: reportportal/service-auto-analyzer
    newTag: 5.7.5
  - name: service-api
    newName: reportportal/service-api
    newTag: 5.8.0
  - name: service-index
    newName: reportportal/service-index
    newTag: 5.8.0
  - name: service-jobs
    newName: reportportal/service-jobs
    newTag: 5.8.0
  - name: migrations
    newName: reportportal/migrations
    newTag: 5.8.0
  - name: service-authorization
    newName: reportportal/service-authorization
    newTag: 5.8.0
  - name: service-ui
    newName: reportportal/service-ui
    newTag: 5.12.0