resources:
  - ./rabbitmq-service.yml
  - ./rabbitmq-stateful-set.yml

secretGenerator:
  - name: rabbitmq
    literals:
      - RABBITMQ_USERNAME=reportportal
      - RABBITMQ_PASSWORD=reportportal_password

images:
  - name: rabbitmq
    newName: docker.io/bitnami/rabbitmq
    newTag: 3.13.7
