resources:
  - ./minio-service.yml
  - ./minio-stateful-set.yml

secretGenerator:
  - name: minio
    namespace: reportportal
    literals:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio_password
