apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: minio
  name: minio
  namespace: reportportal
spec:
  ports:
    - name: minio-api
      port: 9000
      targetPort: minio-api
  selector:
    app.kubernetes.io/name: minio
