apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: reportportal
  labels:
    app.kubernetes.io/name: minio
spec:
  replicas: 1
  serviceName: minio
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
    spec:
      containers:
        - image: minio
          name: minio
          imagePullPolicy: IfNotPresent
          env:
            - name: BITNAMI_DEBUG
              value: "true"
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  key: MINIO_ROOT_USER
                  name: minio
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MINIO_ROOT_PASSWORD
                  name: minio
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /minio/health/live
              port: minio-api
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          ports:
            - containerPort: 9000
              name: minio-api
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: minio-api
            timeoutSeconds: 1
          resources:
            limits: { }
            requests:
              cpu: 25m
              memory: 64Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          volumeMounts:
            - mountPath: /data
              name: data
      securityContext:
        fsGroup: 1001
      serviceAccountName: default
      volumes: null
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi