resources:
  - ./postgres-service.yml
  - ./postgres-stateful-set.yml

secretGenerator:
  - name: postgres
    literals:
      - POSTGRES_POSTGRES_PASSWORD=postgres_password
  - name: postgres-user
    literals:
      - POSTGRES_USER=reportportal
      - POSTGRES_PASSWORD=reportportal_password

configMapGenerator:
  - name: postgres-initdb
    files:
      - ./reportportal-initdb.sh

images:
  - name: postgresql
    newName: docker.io/bitnami/postgresql
    newTag: 12.15.0
