apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: reportportal
  labels:
    app.kubernetes.io/name: postgres
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
