#!/bin/sh
export PGPASSWORD="${POSTGRES_POSTGRES_PASSWORD}"
psql -U postgres -d "${POSTGRES_DB}" \
  -c 'CREATE EXTENSION IF NOT EXISTS ltree; CREATE EXTENSION IF NOT EXISTS pgcrypto; CREATE EXTENSION IF NOT EXISTS pg_trgm;'
